### PR TITLE
Update action.yml

### PR DESCRIPTION
**Pull request by ctdeakin**
Update action.yml to use node20 because node16 is deprecated

### CODE REVIEW

**Comment by uncenter** [comment]
Thanks, I was about to do this. You could probably update the PR title to be more descriptive of the changes fyi.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by bjesuiter** [comment]
Can this be merged? Would be nice to get rid of the warning! :)

**Comment by kt3k** [comment]
Thanks for contributions and feedbacks! We'll release soon after basic testing of the new version

**Pull request merged**
