### PR TITLE
Add .tool-versions and .dvmrc support

### PR DESCRIPTION
**Pull request by jessedijkstra**
Adds support for both .tool-versions and .dvmrc, implementation mirrors that of [setup-node](https://github.com/actions/setup-node/blob/c2ac33f2c62f978d6c944d9648125a294e56dc0b/src/util.ts#L67)

### CODE REVIEW

**Comment by jessedijkstra** [comment]
@kt3k could you take a look at this? Currently required to use asdf in a repository that uses Deno but rather use the setup-deno action with .tool-versions.

**Comment by kt3k** [comment]
Thanks for your contribution!

Can you add test cases in `.github/workflows/test.yml`? Probably by adding something like the below (together with fixture `.dvmrc` and `.tool-versions` files) :

```yml
  # ...
  test-version-file:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [".tool-versions", ".dvmrc"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: ./
        with:
          deno-version-file: ${{ matrix.file }}

      - name: Check version
        run: deno -V | grep -q "deno 1\.43\.1"
```

**Comment by jessedijkstra** [comment]
@kt3k found a bug and fixed it by adding the tests, can you take a look again?

**Comment by jessedijkstra** [comment]
Btw, based on the work of https://github.com/denoland/setup-deno/pull/54 :)

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
